services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_test
      POSTGRES_DB: foodlink_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - foodlink-network

  backend:
    container_name: adonis_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: development
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres_user
      PG_PASSWORD: postgres_test
      PG_DB_NAME: foodlink_db
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
    networks:
      - foodlink-network


networks:
  foodlink-network:
    driver: bridge

volumes:
  postgres_data: