services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_test
      POSTGRES_DB: foodlink_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: